name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'      
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Conda info
      run: conda info
    - name: Conda list
      run: conda list
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file daenv.yml --name base
    - name: Download da_data_repo
      run: |
        curl -L0 https://osf.io/download/9gw4a/ --output da_data_repo.zip
        unzip da_data_repo.zip
    - name: Run test
      run: |
        python run ch00-tech-prep/test_env.py
