name: CI with Conda

on: [push]

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache Conda environment
        id: cache-conda
        uses: actions/cache@v3
        with:
          path: ~/.conda/envs
          key: ${{ runner.os }}-conda-${{ hashFiles('daenv.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Install Conda and set up environment
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda init bash
          conda config --set always_yes yes
          conda update -q conda
          conda env create -f daenv.yml

      - name: Download da_data_repo
        run: |
          curl -L0 https://osf.io/download/9gw4a/ --output da_data_repo.zip
          unzip da_data_repo.zip

      - name: Run tests
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda activate daenv
          python ch00-tech-prep/test_env.py
