name: CI with Conda

on: [push]

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Conda
        uses: s-weigand/setup-conda@v1
    
      - name: Install dependencies
        run: |
          conda env create -f daenv.yml

      - name: Cache Conda environment
        id: cache-conda
        uses: actions/cache@v3
        with:
          path: ~/.conda/envs
          key: ${{ runner.os }}-conda-${{ hashFiles('daenv.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Update environment
        run: conda env update -n daenv -f daenv.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Download da_data_repo
        run: |
          curl -L0 https://osf.io/download/9gw4a/ --output da_data_repo.zip
          unzip da_data_repo.zip

      - name: Run tests
        run: |
          conda init
          conda activate daenv
          python ch00-tech-prep/test_env.py
